swagger: "2.0"
info:
  title: Technozion APIs
  desccription: This contains documentation of all APIs from backend
  version: "2.0.0"
  contact:
    email: rohitrajeev02@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org
  server:
    - url: http://localhost:5000
      description: Local Server
    - url: https://technozion-22.herokuapp.com
      description: Remote Server
  schemes: [http, https]

  paths:
    /auth/signin:
        post:
          summary: Sign in data
          consumes:
            - application/json
          parameters:
            - in: body
              name: user
              description: The user to signin
              schema:
                type: object
                required:
                  - email
                  - password
                properties:
                  email:
                    type: string
                  password:
                    type: string
          responses:
            200:
              description: Success
